### PR TITLE
Allocate linresp input only on demand

### LINKED ISSUE #945: Inconsistent option "EigenvectorsAsText = No" in dftb_pin.hsd
**Describe the bug**
The contents of the file "dftb_pin.hsd" seem to change, even though the original file "dftb_in.hsd" stays the same.
Specifically, the option "EigenvectorsAsText = No" seems to sometimes appear in "dftb_pin.hsd", and sometimes not.

**To Reproduce**
1) Download the stable source from https://dftbplus.org/download/dftb-stable
2) Compile using the instructions given at https://github.com/dftbplus/dftbplus
3) Use the dftb_in.hsd-file given at https://dftbplus-recipes.readthedocs.io/en/latest/basics/firstcalc.html
4) Run the program in _build/app/dftb+ like `./dftb+ && grep "Eigenvectors" dftb_pin.hsd`

**Additional Info**
1. Input-file see above, the only thing I changed is the location of the SK-files
2. DFTB+ Version 21.2, compiled from source (see above), gfortran 9.3.0, cmake 3.16.3 on Ubuntu 20.4.3 LTS
3. For me, sometimes the option "EigenvectorsAsText = No" appears in the dftb_pin.hsd-file, and sometimes it does not. It may take a few runs to see it happening.

I just recently started working with dftb+, so I just might be missing something, apologies if that is the case. The behaviour just seems strange to me. I did not make any changes to the code.

### PR DESCRIPTION
**Pull request by aradi**
Rationalize the usage of the linresp input type.

Closes #945

### CODE REVIEW

File: src/dftbp/dftbplus/initprogram.F90 [hunk 1]
```diff
@@ -5227,6 +5227,8 @@ subroutine ensureLinRespConditions(tSccCalc, t3rd, tRealHS, tPeriodic, tCasidaFo
 
     character(lc) :: tmpStr
 
+    @:ASSERT(allocated(input%ctrl%lrespini))
```
Comment (bhourahine) [inline src/dftbp/dftbplus/initprogram.F90:5230]: Could just return true if not allocated

**Review by bhourahine — APPROVED** [review]
Looks fine, but see suggestion about ensureLinRespConditions (which is quite a long routine name, but that's a separate issue...)

File: src/dftbp/dftbplus/initprogram.F90 (hunk 1 above)
Comment (bhourahine) [reply src/dftbp/dftbplus/initprogram.F90:5230]:
```suggestion
    if (.not.allocated(input%ctrl%lrespini)) then
      return
    end if
```

**Review by awvwgk — APPROVED** [review]
