### PR TITLE
Guard MPI related poisson imports by additional branch

### LINKED ISSUE #1117: Compiling without POISSON blows up
**Describe the bug**
Compiling with the flags `-DWITH_MPI=1 -DWITH_POISSON=0` results in:
```
/home/user/dftbplus/_build/src/dftbp/extlibs/poisson.f90(21): error #7002:
Error in opening the compiled module file.  Check INCLUDE paths.   [DFTBP_POISSON_POISSON]
  use dftbp_poisson_poisson, only : global_comm, poiss_mpi_init, poiss_mpi_split
------^
/home/user/dftbplus_test/_build/src/dftbp/extlibs/poisson.f90(21): error #6580: Name in only-list does not exist or is not accessible.   [GLOBAL_COMM]
  use dftbp_poisson_poisson, only : global_comm, poiss_mpi_init, poiss_mpi_split
------------------------------------^
/home/user/dftbplus_test/_build/src/dftbp/extlibs/poisson.f90(21): error #6580: Name in only-list does not exist or is not accessible.   [POISS_MPI_INIT]
  use dftbp_poisson_poisson, only : global_comm, poiss_mpi_init, poiss_mpi_split
-------------------------------------------------^
/home/user/dftbplus_test/_build/src/dftbp/extlibs/poisson.f90(21): error #6580: Name in only-list does not exist or is not accessible.   [POISS_MPI_SPLIT]
  use dftbp_poisson_poisson, only : global_comm, poiss_mpi_init, poiss_mpi_split
```
I'm surprised this isn't blowing up in the GitHub workflows/buildbot runs. Maybe it's just me, I don't have time for more testing right now.

**To Reproduce**
Compile DFTB+ with above mentioned flags.

**Expected behaviour**
DFTB+ should compile without errors (as before #1115?).

### PR DESCRIPTION
**Pull request by vanderhe**
Presumably fixes #1117.

### CODE REVIEW

**Comment by vanderhe** [comment]
Buildbot tests still running, but since the error I've encountered in #1117 was not noticed before this is probably pointless.

File: src/dftbp/extlibs/poisson.F90 [hunk 1]
```diff
@@ -35,6 +34,9 @@ module dftbp_extlibs_poisson
       & set_poissonbox, set_poissongrid, set_accuracy, set_verbose, check_biasdir,&
       & check_poisson_box, check_parameters, check_localbc, check_contacts, write_parameters,&
       & poiss_getlatvecs
+#:if WITH_MPI
```
Comment (bhourahine) [inline src/dftbp/extlibs/poisson.F90:37]: Not sure, but indenting the inner macro might be easier to read (but leave the actual use statement in place).

**Review by bhourahine — APPROVED** [review]

File: src/dftbp/extlibs/poisson.F90 (hunk 1 above)
Comment (vanderhe) [reply src/dftbp/extlibs/poisson.F90]: Yeah, I wasn't sure either. I've indented the macro by two spaces now.
